function init(self)
	self.pos = go.get_position()
	msg.post(".", "acquire_input_focus")
	self.pos.z = 1
	self.hover = nil
	self.menu = nil
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	print(self.menu)
	go.set_position(self.pos)
	self.hover = nil
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.other_group == hash("Zombie") then
			self.hover = message.other_id
		end
	end
end

function on_input(self, action_id, action)
	self.pos.x = action.x
	self.pos.y = action.y
	if action_id == hash("l_click") and action.pressed then
		msg.post("/Player", "cast_melee")
		--[[if self.hover ~= nil then
			local player = go.get_position("/Player")
			local cursor = go.get_position("/Cursor")
			local enemy = go.get_position(self.hover)
			local ray = physics.raycast(player, cursor, {hash("Obstacle"), hash("Zombie")})
			if math.abs(player.x - enemy.x) < 32 and math.abs(player.y - enemy.y) < 32 then
				msg.post(self.hover, "get_dead")
			end
		end--]]
	end
	if action_id == hash("r_click") and action.pressed then
		msg.post("/Player", "cast_melee")
		msg.post("/defluid", "cast_scab")
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
